package com.omar.spring_with_ai;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;


/**
 * REST controller responsible for generating recipe suggestions using Spring AI.
 * This controller exposes an endpoint that accepts a user message (prompt)
 * and returns a response generated by the configured AI model via ChatClient.
 * Base URL: /recipes
 */
@RestController
@RequestMapping("/recipes")
public class RecipesController {

    /**
     * ChatClient is the Spring AI abstraction used to communicate with the
     * AI model (OpenAI, Ollama, VertexAI, etc.). It allows sending messages
     * and receiving AI-generated responses.
     */
    private final ChatClient chatClient;

    /**
     * Constructor-based dependency injection for the ChatClient.
     * <p>
     * Spring automatically injects a {@link ChatClient.Builder}, which is then
     * customized by adding a {@link SimpleLoggerAdvisor} before building the
     * final immutable {@link ChatClient} instance.
     * </p>
     *
     * <p>
     * The {@code SimpleLoggerAdvisor} enables logging of prompts, responses,
     * and model interactions, which is useful for debugging and understanding
     * how the AI behaves at runtime.
     * </p>
     *
     * @param chatClientBuilder the builder used to configure and create the ChatClient
     */
    public RecipesController(ChatClient.Builder chatClientBuilder) {
        this.chatClient = chatClientBuilder
                .defaultAdvisors(new SimpleLoggerAdvisor())
                .build();
    }

    /**
     * Generates a recipe suggestion based on a user message.
     * Example request:
     *     GET /recipes/suggest-recipe?message=Suggest a quick breakfast
     * <p>
     * If no message is provided, the default message is:
     *     "Suggest a recipe for dinner"
     *
     * @param message User prompt for requesting recipe suggestions
     * @return AI-generated recipe suggestion as plain text
     */
    @GetMapping("/suggest-recipe")
    public String suggestRecipe(
            @RequestParam(
                    name = "message",
                    defaultValue = "Suggest a recipe for dinner"
            ) String message
    ) {
        // Build a chat prompt with the user message and send it to the AI model
        return this.chatClient.prompt()
                .user(message)    // Add user prompt
                .call()           // Execute request
                .content();       // Extract the AI response
    }

}